#!/bin/bash
#This routine set dimensions for the find-rectangle-center.ngc routine

(sleep 1 && wmctrl -F -a "Inserisci dati" -b add,above) &
yad_data=$(yad --title "Inserisci dati"  --text="Inserisci dimensioni del rettangolo (in mm)" --form --field "Lunghezza X" --field="Lunghezza Y" --field="Altezza Z")

x=$(echo $yad_data | awk 'BEGIN {FS="|" } { print $1 }')
y=$(echo $yad_data | awk 'BEGIN {FS="|" } { print $2 }')
z=$(echo $yad_data | awk 'BEGIN {FS="|" } { print $3 }')

if [ ! -z "$x" ]; then
 sed -i "10s/.*/#<_x_lenght> = $x/" /home/ciccio/linuxcnc/configs/10060_3axis/routines/find-rectangle-center.ngc
fi

if [ ! -z "$y" ]; then
 sed -i "11s/.*/#<_y_lenght> = $y/" /home/ciccio/linuxcnc/configs/10060_3axis/routines/find-rectangle-center.ngc
fi

if [ ! -z "$z" ]; then
 sed -i "12s/.*/#<_z_lenght> = $z/" /home/ciccio/linuxcnc/configs/10060_3axis/routines/find-rectangle-center.ngc
fi

exit 0
