#!/bin/bash

(sleep 1 && wmctrl -F -a "Probe" -b add,above) &
yad --title "Probe" --image=/home/ciccio/linuxcnc/configs/10060_4th/M-codes/qs.png --geometry="290x120" --text="<big>Hai fatto il probe? Hai posizionato il mandrino in un punto dove poter cambiare l'utensile?</big>" --button="STOP" --button="Continua"

case $? in
    0)halcmd setp halui.program.stop True 
      sleep 3
      halcmd setp halui.program.stop False
    ;;
esac
exit 0
